In [1]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

In [2]:
model_name = 'ProsusAI/finbert'

In [3]:
# inilialize our model and tokenizer
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [42]:
txt2= """The world is a small place, and so, deeds of one person may have repercussions on another person. Speaking on a similar note, the tug of war between the two Indian states of Haryana and Punjab and the Capital of Delhi has conspicuously grabbed everyone’s attention.

While the country’s capital is adamant on putting all the blame on the agricultural states for the increased air degradation in Delhi, the neighbouring states seem to be prepared to shrug the blame off their own shoulders. What could be more brazen than the Nirbhaya rape case victim pleading for mercy, claim that the life span of people in Delhi has already reduced due to pollution! When your country’s capital is allegedly the most polluted city in the world, it is hard to save yourself from embarrassment in the eyes of the world.

Repetitive warnings and questions being hurled upon the government by the Supreme Court and the citizens of India seem to all be in vain. Amidst all the political drama, a variety of opinions and supposed solutions can be seen getting the limelight. While some people demand a complete ban on stubble burning, others seem to have a soft corner for the poor farmers.

Several suggestions propose using the “Happy Seeder” machine instead of stubble burning. The government has a scheme of providing subsidy to farmers up to 50% when it comes to purchasing Happy Seeder. Notwithstanding the fact that the cost price of one unit of Happy Seeder is not less than Rs 4-5 lakhs, and even half of the sum is quite a huge amount when the average income of a farmer is estimated at Rs 77,976 per year, according to the Dalwai Committee Report.
This income can barely afford any extravagant expenses; it is already quite burdensome for most of the farmers to get their ends meet. Even if such a huge amount is somehow borne by the farmer, the machine would remain idle for the better part of the year.

A possible solution to this problem could be that the government itself undertakes a contract with a Happy Seeder manufacturing company and under the postulates of the contract, the company could be urged to rent their machines to the seeking farmers for the stipulated time period. Not to mention that the cost to be borne by the peasants would decrease drastically.

I came across an article by Mr Ajay Shankar, a distinguished member of TERI. He had put forward some of the brilliant two-way income opportunities from the crop residue. After treatment, the stubble can be used for cattle rearing. Another way to use it would be to convert it into biofuel for vehicles. In fact, Mahindra Group Company and IGL have joined hands for this concept.

Yet another way of making a profit from stubble is to convert it into briquettes. Briquettes, a substitute for coal, has a potent market in current times. It has primary usage in thermal power plants. Many companies have been lured by the fact that briquettes use no extra power as a replacement of coal and its sufficient availability is undeniable.

A scheme could be launched where the companies purchase stubble at a price ample for them to make a decent profit out of it even after covering the cost of harvesting the residue and then, convert it into briquettes. This solution can possibly eliminate stubble burning in a very short period of time.


"""

In [74]:
txt= """India’s Finance Minister Nirmala Sitharaman announced optimistic projections for India’s economic future at the Vibrant Gujarat Global Summit. She predicts India will overtake Germany and Japan to become the third-largest economy by 2027–28, boasting a GDP exceeding $5 trillion. By 2047, she estimates a conservative reach of $30 trillion, solidifying India’s economic standing.

This ambitious forecast builds on India’s current position as the world’s fifth-largest economy, with a GDP of roughly $3.4 trillion. Additionally, the economy is projected to grow by a robust 7.3% in the current fiscal year, surpassing the 7.2% growth of 2022–23.

Sitharaman further highlighted the success of foreign direct investment (FDI) in India, attracting $919 billion in the past 23 years, with 65% secured in the past 8–9 years under the current government. This surge in FDI demonstrates investor confidence in India’s economic potential.

"""

In [43]:
#tokens = tokenizer.encode_plus(txt2,add_special_tokens=False,return_tensors='pt')

In [77]:
tokens = tokenizer.encode_plus(txt,add_special_tokens=False,return_tensors='pt')

In [78]:
len(tokens['input_ids'][0]),tokens

(207,
 {'input_ids': tensor([[ 2634,  1521,  1055,  5446,  2704,  9152, 17830,  2721,  4133, 11077,
           2386,  2623, 21931, 21796,  2005,  2634,  1521,  1055,  3171,  2925,
           2012,  1996, 17026, 14288,  3795,  6465,  1012,  2016, 16014,  2015,
           2634,  2097,  2058, 15166,  2762,  1998,  2900,  2000,  2468,  1996,
           2353,  1011,  2922,  4610,  2011, 16798,  2581,  1516,  2654,  1010,
           8945, 14083,  2075,  1037, 14230, 17003,  1002,  1019, 23458,  1012,
           2011, 19627,  2581,  1010,  2016, 10035,  1037,  4603,  3362,  1997,
           1002,  2382, 23458,  1010,  5024, 11787,  2634,  1521,  1055,  3171,
           3061,  1012,  2023, 12479, 19939, 16473,  2006,  2634,  1521,  1055,
           2783,  2597,  2004,  1996,  2088,  1521,  1055,  3587,  1011,  2922,
           4610,  1010,  2007,  1037, 14230,  1997,  5560,  1002,  1017,  1012,
           1018, 23458,  1012,  5678,  1010,  1996,  4610,  2003, 11310,  2000,
           4982,  20

In [79]:
input_ids = tokens['input_ids']
attention_mask = tokens['attention_mask']

In [80]:
len(tokens['input_ids'][0])

207

In [81]:
input_id_chunk = tokens['input_ids'][0].split(200)
mask_chunk = tokens['attention_mask'][0].split(200)

In [82]:
len(input_id_chunk)

2

In [84]:
input_id_chunk[1]

tensor([1999, 2634, 1521, 1055, 3171, 4022, 1012])

In [85]:
a= torch.arange(10)

In [86]:
a = torch.cat(
    [torch.Tensor([101]),a, torch.Tensor([102])]
)
a

tensor([101.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9., 102.])

In [87]:
padding_len = 20-a.shape[0]
padding_len


8

In [88]:
if padding_len >0:
  a= torch.cat(
      [a,torch.Tensor([0] * padding_len)]
  )
  a, len(a)

In [91]:
chunk_size = 209

input_id_chunks = list(tokens['input_ids'][0].split(chunk_size - 2))
mask_chunks = list(tokens['attention_mask'][0].split(chunk_size - 2))

for i in range(len(input_id_chunks)):
    # add special tokens
    input_id_chunks[i] = torch.cat(
        [torch.Tensor([101]), input_id_chunks[i], torch.Tensor([102])]
    )
    mask_chunks[i] = torch.cat(
        [torch.Tensor([1]), mask_chunks[i], torch.Tensor([1])]
    )

    # padding
    padding_len = chunk_size - input_id_chunks[i].shape[0]

    if padding_len > 0:
        input_id_chunks[i] = torch.cat(
            [input_id_chunks[i], torch.Tensor([0] * padding_len)]
         )
        mask_chunks[i] = torch.cat(
            [mask_chunks[i], torch.Tensor([0] * padding_len)]
         )

In [92]:
_ = [print(len(chunk)) for chunk in input_id_chunks]

209


In [93]:
input_ids = torch.stack(input_id_chunks)
attention_mask = torch.stack(mask_chunks)

In [94]:
input_ids

tensor([[  101.,  2634.,  1521.,  1055.,  5446.,  2704.,  9152., 17830.,  2721.,
          4133., 11077.,  2386.,  2623., 21931., 21796.,  2005.,  2634.,  1521.,
          1055.,  3171.,  2925.,  2012.,  1996., 17026., 14288.,  3795.,  6465.,
          1012.,  2016., 16014.,  2015.,  2634.,  2097.,  2058., 15166.,  2762.,
          1998.,  2900.,  2000.,  2468.,  1996.,  2353.,  1011.,  2922.,  4610.,
          2011., 16798.,  2581.,  1516.,  2654.,  1010.,  8945., 14083.,  2075.,
          1037., 14230., 17003.,  1002.,  1019., 23458.,  1012.,  2011., 19627.,
          2581.,  1010.,  2016., 10035.,  1037.,  4603.,  3362.,  1997.,  1002.,
          2382., 23458.,  1010.,  5024., 11787.,  2634.,  1521.,  1055.,  3171.,
          3061.,  1012.,  2023., 12479., 19939., 16473.,  2006.,  2634.,  1521.,
          1055.,  2783.,  2597.,  2004.,  1996.,  2088.,  1521.,  1055.,  3587.,
          1011.,  2922.,  4610.,  1010.,  2007.,  1037., 14230.,  1997.,  5560.,
          1002.,  1017.,  10

In [95]:
input_dict = {
    "input_ids":input_ids.long(),
    "attention_mask":attention_mask.int()
}
input_dict

{'input_ids': tensor([[  101,  2634,  1521,  1055,  5446,  2704,  9152, 17830,  2721,  4133,
          11077,  2386,  2623, 21931, 21796,  2005,  2634,  1521,  1055,  3171,
           2925,  2012,  1996, 17026, 14288,  3795,  6465,  1012,  2016, 16014,
           2015,  2634,  2097,  2058, 15166,  2762,  1998,  2900,  2000,  2468,
           1996,  2353,  1011,  2922,  4610,  2011, 16798,  2581,  1516,  2654,
           1010,  8945, 14083,  2075,  1037, 14230, 17003,  1002,  1019, 23458,
           1012,  2011, 19627,  2581,  1010,  2016, 10035,  1037,  4603,  3362,
           1997,  1002,  2382, 23458,  1010,  5024, 11787,  2634,  1521,  1055,
           3171,  3061,  1012,  2023, 12479, 19939, 16473,  2006,  2634,  1521,
           1055,  2783,  2597,  2004,  1996,  2088,  1521,  1055,  3587,  1011,
           2922,  4610,  1010,  2007,  1037, 14230,  1997,  5560,  1002,  1017,
           1012,  1018, 23458,  1012,  5678,  1010,  1996,  4610,  2003, 11310,
           2000,  4982,  20

The model will give softmax outputs for three labels: positive, negative or neutral.

In [96]:
output = model(**input_dict)
probs = torch.nn.functional.softmax( output[0], dim=-1)
probs = probs.mean(dim=0)
probs

tensor([0.9414, 0.0152, 0.0433], grad_fn=<MeanBackward1>)

In [ ]:
#As we can see, txt is highly positive!

In [68]:
torch.argmax(probs).item()

2